require 'rack/initforthe/facebook/version'
require 'rack/initforthe/facebook/signed_request'
require 'rack/initforthe/facebook/method_fix'
require 'rack/initforthe/facebook/like_gate'
require 'rack/initforthe/facebook/app_data_redirect'